#!/bin/bash

grep '<td>\(..*\)<\/td>' | sed 's/.*<td>\(..*\)<\/td>/\1/g' | sed 's/<[^>]*>//g' | sed '1~2d' |  sed 's/\ /\n/g' | sed "s/\`/'/g" | sed 's/,/\n/g' | tr '[:upper:]' '[:lower:]' | grep -v "[^'aeiouhlwnmkp]" | awk 'NF' | sort -u
